"""Agregar campo created_at a CartItem

Revision ID: 861c37b3a10b
Revises: 815ba017915f
Create Date: 2025-04-08 05:09:22.072340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '861c37b3a10b'
down_revision = '815ba017915f'
branch_labels = None
depends_on = None


def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartitem', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cartitem', 'created_at')
    # ### end Alembic commands ###