services:
 
   ecommerce_app:
     tty: true
     build:
       context: .
       args:
         requirements: requirements/reqs.txt
     container_name: contenedor_ecommerce_app
     env_file:
      - .env
     environment:
       # use in code
       - DEBUG=True
       - PYTHONUNBUFFERED=1
       - JWT_SECRET_KEY=${JWT_SECRET_KEY} #Esto es para que mi contenedor reconozca mi varible de ambiente.
     volumes:
       - .:/app:delegated
     ports:
       - 8001:8001
     depends_on:
       - postgres 
     command: sh -c "wait-for-it postgres:5432 -- uvicorn main:app --host 0.0.0.0 --port 8001 --reload"

   postgres:
     image: postgres:14
     container_name: contenedor_ecommerce_postgres
     environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
       - POSTGRES_DB=ecommerce_db
     ports:
       - 5432:5432